puts "1. Seeding Admin"
  User.create!(name: "Admin", email: "admin@gmail.com", password: "123456", role: 1, username: "admin", phone: "123456", address: "KTX Đại học FPT, Hòa Lạc", dob: DateTime.now)

puts "2. Seeding Doctor"
5.times do |i|
  User.create!(name: "Doctor#{i}", email: "doctor#{i}@gmail.com", password: "123456", role: 2, username: "doctor#{i}", phone: "123456", address: "KTX Đại học FPT, Hòa Lạc", dob: DateTime.now)
end

puts "3. Seeding Secretary"
  User.create!(name: "Secretary", email: "secretary@gmail.com", password: "123456", role: 5, username: "secretary", phone: "123456", address: "KTX Đại học FPT, Hòa Lạc", dob: DateTime.now)

puts "4. Seeding User"
20.times do |i|
  User.create!(name: FFaker::Name.unique.name, email: "user#{i}@gmail.com", password: "123456", role: 0, username: "user#{i}", phone: "123456", address: "KTX Đại học FPT, Hòa Lạc", dob: DateTime.now)
end
puts "5. Seeding Director"
  User.create!(name: "Director", email: "director@gmail.com", password: "123456", role: 4, username: "director", phone: "123456", address: "KTX Đại học FPT, Hòa Lạc", dob: DateTime.now)

puts "6. Seeding Nurse"
5.times do |i|
  User.create!(name: "Nurse#{i}", email: "nurse#{i}@gmail.com", password: "123456", role: 3, username: "nurse#{i}", phone: "123456", address: "KTX Đại học FPT, Hòa Lạc", dob: DateTime.now)
end

puts "7. Seeding Desease"
    Desease.create!(pet_type: 1,
                    name: "Bênh dại",
                    symptom: "nhớt dãi, hay ngáp, đồng tử mắt dãn ra, giảm ăn, hành động có chiều hướng hung hãn, giai đoạn cuối tê liệt, suy hô ",
                    reason: "Virus dại chủ yếu lây truyền qua các vết cắn, vết liếm vào vết thương của một số động vật mắc bệnh dại. Trong một số ít trường hợp, bệnh có thể lây truyền qua đường hô hấp.",
                    treatment: "Tính tới thời điểm hiện tại chưa phương pháp hoặc thuốc điều trị nào cho mèo bị bệnh dại. Cách tốt nhất là iêm vacxin phòng dại cho mèo theo định kỳ hàng . Hạn chế tiếp xúc với những con vật có biểu hiện bệnh dại",
                    description: "Bệnh dại là căn bệnh viêm nhiễm virus lây truyền qua vết cắn của một con vật đã nhiễm bệnh,nhiễm trùng gây ảnh hưởng trực tiếp tới hệ thần kinh trung ương, làm cho mèo bị sốt và có  những động thái khác thường.")
    Desease.create!(pet_type: 1,
                    name: "Nhiễm trùng đường hô hấp",
                    symptom: "Hắt xì, chảy nước mắt, đồ ghèn, ho, khó thở, sổ mũi, ăn không ngon, biếng ăn kéo dài, sốt kéo dài, viêm phổi do không được chữa trị",
                    reason: "Trong khi những bệnh siêu vi có một tỷ lệ mắc bệnh cao ở mèo con, thì bệnh Chlamydia này xuất hiện ở tất cả các lứa tuổi và tất cả các giống mèo, tỉ lệ nhiễm cao khi mèo được nuôi nhót và có tỉ lệ con trong đàn cao, hay nuôi trong củi thay vì nuôi tự do hoặc nơi có nguy cơ nhiễm trùng cao. Bệnh rất dễ lây lan vì vi khuẩn được phát tán một cách dễ dàng, sự lan truyền bệnh có thể xảy ra ngay cả khi không tiếp xúc trực tiếp với một con vật bị nhiễm bệnh, các vi khuẩn từ mèo bệnh khi ho hoặc hắt hơi ra ngoài không khí, có thể được phát tán đi xa hoặc dính vào quần áo người chăm sóc thú rồi từ đó có thể mang vi khuẩn qua những đàn khác và làm lây lan bệnh khi tiếp xúc với thú khỏe, hoặc mèo có thể tiếp xúc với các vật dụng bị nhiễm khuẩn, chẳng hạn như ổ nằm hoặc tô, bát chứa thức ăn…",
                    treatment: "Điều trị bệnh nhiễm trùng đường hô hấp trên của mèo thường là điều trị ngoại trú, bắt đầu với các loại thuốc kháng sinh như Tetracycline hoặc Doxycycline. Kháng sinh có thể cho uống hoặc dùng bên ngoài như nhỏ hay xịt vào mắt. Toàn bộ quá trình điều trị có thể mất đến sáu tuần.",
                    description: "Là 1 bệnh cấp tính về đường hô hấp trên ở mèo do virus Feline herpes gây nên. Virus feline herpes là virus phổ biến nhất gây nên các dịch  bệnh về đường hô hấprên ở mèo, lây lan rất nhanh đối với mèo con và mèo được nuôi nhốt tập thể như các trại mèo hay tại các hộ gia  đình nuôi nhiều mèo. Mèo con và mèo già dễ lây bệnh cũng như có nguy cơ tử vong cao hơn mèo trưởng thành khỏe mạnh. Một khi mèo bị nhiễm virus feline herpes, nó sẽ tồn tại suốt cuộc đời cá thể mèo.")
    Desease.create!(pet_type: 1,
                    name: "Bệnh Feline Panleukopenia (FP)",
                    symptom: "Bỏ ăn uống, dáng đi uể oải, di chuyển ít, hay gập người đau đớn, nôn, tiêu chảy, tiêu chảy ra máu, mất nước, giảm cân, sốt cao, thiếu máu, lông thô cứng, trầm cảm, chán ăn, bàn chân giấu bên dưới cơ thể trong thời gian dài, mệt mỏi, cơ thể thiếu linh hoạt, các triệu chứng thần kinh vì virus tấn công vào não bộ như đi loạng choạng, mất thăng bằng, cơ thể run rẩy lắc lư, co giật, co giật, tử vong",
                    reason: "Bệnh Felnine Penleukopenia rất dễ lây lan. Nó hiện diện bất cứ nơi nào nhưng không lây truyền sang chó. Virus Panleukopenia lây lan trực tiếp qua sự tiếp xúc của mèo khỏe mạnh với mèo bị nhiễm bệnh. Hoặc khi tiếp xúc với chất bài tiết của mèo bệnh như phân, nước tiểu, nước bọt và chất nôn mửa… Sự nhiễm trùng sẽ lây lan qua đường hô hấp hoặc việc tiêu hóa chất lây nhiễm. Bọ chét và ruồi cũng có thể là nguyên nhân lan truyền bệnh này. Ngoài ra, thực phẩm, quần áo hoặc bàn tay tiếp xúc của người từ mèo bệnh sang mèo khỏe cũng có thể làm lây lan bệnh. Virus Panleukopenia có sức sống bền bỉ. Nó có thể tồn tại nhiều năm trong môi trường bị ô nhiễm. Mèo con trong độ tuổi từ 2 – 6 tháng có nguy cơ mắc bệnh cao nhất cũng như mèo mang thai và mèo bị tổn hại hệ miễn dịch.",
                    treatment: "Đến nay vẫn chưa có cách chữa trị cụ thể cho bệnh này. Việc điều trị thông thường bao gồm sự chăm sóc đặc biệt cho chú mèo của bạn. Việc này nhằm giúp cơ thể chúng có thể sản xuất đủ kháng thể và trung hòa virus như tiêm thuốc kháng sinh. Chống lại việc nhiễm trùng và xâm nhập của các vi khuẩn thứ cấp. Đặc biệt là các loại vi khuẩn xâm nhập vào đường ruột. Ngoài ra, chủ nuôi cần bổ sung nước uống cho mèo. Để chống mất nước nên bổ sung vitamin. Kiểm soát việc nôn mửa và tiêu chảy. Giữ ấm cơ thể cho chúng. Mèo lúc này đặc biệt rất cần sự yêu thương và vuốt ve. Nếu chúng có thể sống sót trong vòng 5 ngày từ khi mắc bệnh thì chúng sẽ có nhiều cơ hội để phục hồi hơn. Điều đặc biệt quan trọng là phải cách ly ngay mèo bị nghi ngờ nhiễm bệnh vói những con mèo khác. Khử trùng khu vực cách ly và các vật dụng dành cho chúng. Việc cách ly sẽ ngăn chặn sự lây lan của căn bệnh. Sau đó, tốt nhất hãy đưa chúng tới bệnh viện thú y gần nhất để điều trị.",
                    description: "Bệnh Felnine Penleukopenia ở mèo (hay còn gọi là Bệnh Giảm Bạch Cầu – Viêm Ruột Truyền Nhiễm). Đây là bệnh do virus Feline Panleukopenia (FPV) thuộc nhóm virus Parvovirus gây ra cho hầu hết tất cả các giống mèo.")
    Desease.create!(pet_type: 1,
                    name: "Bệnh FIV",
                    symptom: " Nhiễm trùng răng miệng,Bệnh về đường hô hấp, bệnh về mắt, bệnh về đường tiêu hóa, nhiễm trùng da và tai, bệnh về thần kinh, hạch, thiếu máu,ung thư",
                    reason: "Cũng giống như HIV chỉ lây nhiễm cho người, virus FIV chỉ lây truyền qua mèo và không lây lan sang các loại động vật có vú khác, FIV cũng không lây sang người và không có nguy cơ lây nhiễm từ những người tiếp xúc với mèo dương tính với FIV cho những chú mèo bình thường khác. Virus FIV rất dễ bị vô hiệu hóa bởi tia cực tím, nhiệt độ cao, chất tẩy rửa... và FIV thường lây lan thông qua vết cắn từ nước bọt của mèo bệnh nhiễm vào máu và không lây qua đường hô hấp, ăn uống. Mèo đực có khả năng mắc bệnh cao gấp 2 lần mèo cái vì thói quen cắn nhau. Ngoài ra, mèo mẹ bị nhiễm bệnh trong khi mang thai hoặc cho con bú có thể lây nhiễm cho mèo con vì FIV cũng có trong tử cung và sữa mèo dù rất hiếm. Mèo mẹ bị nhiễm FIV trước khi mang thai thường không lây truyền qua mèo con.",
                    treatment: "Thực tế thì vẫn chưa có kháng thể để điều trị một cách cụ thể đối với mèo nhiễm FIV. Và vì mèo có thể mang vi khuẩn trong một thời gian dài trước khi các triệu chứng xuất hiện, nên việc điều trị tập trung chủ yếu vào việc kéo dài giai đoạn không có triệu chứng, hoặc khi các triệu chứng dần biểu hiện ra, nhằm giảm bớt các hoạt động của vi khuẩn theo các dấu hiệu của căn bệnh mà mèo đang mắc phải. Trong suốt quá trình điều trị, chú mèo cần được cung cấp chế độ chăm sóc đặc biệt, dinh dưỡng tốt và tiêm kháng sinh các bệnh nhiễm trùng cơ hội. Nếu chú mèo của bạn là mèo đực, thì chú nên bị thiến để giảm nguy cơ chiến đấu và lây lan nhiễm trùng. Ngoài ra, nên nhốt mèo bệnh trong nhà để hạn chế việc lây lan bệnh sang mèo khác. Duy trì dinh dưỡng chất lượng tốt - tránh thịt, trứng và các sản phẩm từ sữa chưa được tiệt trùng nhằm giảm nguy cơ tiếp xúc với ký sinh trùng và vi khuẩn có thể gây bệnh. Chẩn đoán kịp thời và điều trị thích hợp bệnh FIV tùy theo giai đoạn và những bệnh đang mắc phải nhằm ức chế sự gia tăng của bệnh và vi khuẩn trong cơ thể có thể giúp mèo nhiễm FIV duy trì chất lượng cuộc sống trong một thời gian dài.",
                    description: "Hội chứng suy giảm miễn dịch ở mèo (FIV) là bệnh nhiễm trùng quan trọng đối với họ nhà mèo, có mặt khắp nơi trên thế giới do một loại virus thuộc họ Retrovirus gây ra. Đó là loại virus cùng họ với virus giảm bạch cầu ở mèo (FeLV) và virus gây ra hội chứng suy giảm miễn dịch mắc phải ở người là HIV.")
    Desease.create!(pet_type: 1,
                    name: "Bệnh FIP",
                    symptom: "Các triệu chứng của bệnh FIP thay đổi tuỳ thuộc vào chủng virus có liên quan, tình trạng hệ miễn dịch ở mèo và các cơ quan bị ảnh hưởng. Có hai hình thức được phát hiện, bao gồm dạng ướt (dạng có tiết dịch), tấn công vào các khoang cơ thể và dạng khô (dạng không tiết dịch), tấn công nhiều cơ quan khác nhau. Dạng ướt có xu hướng tiến triển nhanh hơn so với dạng khô. Trong cả hai trường hợp, con mèo ở trong tình trạng cơ thể bị đau, với lớp lông trở nên thô ráp, chúng trở nên ngu si đần độn, và ngày càng trở nên thờ ơ, chán nản. Dạng ướt/Dạng có tiết dịch: Sốt dai dẳng và không hồi đáp, Không muốn ăn, Giảm cân (dần dần), Sự thèm ăn kém, tiêu chảy, Bụng to lên dần dần (bụng phệ, sưng bụng), Tích tụ dịch trong khoang ngực, Khó thở, Hắt hơi, chảy nước mũi, Hôn mê, Dạng khô/Không tiết dịch: Phát triển kém ở mèo con, Thiếu máu, Vàng da, Tiêu chảy, Sốt, Trầm cảm, Viêm các phần khác nhau của mắt, Các triệu chứng thần kinh (ví dụ: mất khả năng điều phối chuyển động, mất thị lực)",
                    reason: "FIP thường theo sau nhiễm virus coronavirus, thường không gây ra bất kỳ triệu chứng bên ngoài nào. Người ta cho rằng có một số loại coronavirus đột biến vào viêm phúc mạc nhiễm trùng, hoặc do chính chúng hoặc do hậu quả của một khiếm khuyết trong đáp ứng miễn dịch của mèo. Mộ điều làm phức tạp vấn đề là một coronavirus có thể nằm im trong cơ thể mèo trong nhiều tháng trước khi đột biến thành FIP. Virus FIP sau đó lây nhiễm vào các tế bào hồng cầu, sử dụng chúng làm phương tiện để xâm nhập toàn bộ cơ thể.",
                    treatment: "Bệnh này rất khó điều trị và cần được chăm sóc hỗ trợ tốt. Với dạng không tiết dịch, điều trị có thể bằng cách sử dụng thuốc kháng sinh, thuốc chống viêm và thuốc ức chế miễn dịch để làm chậm sự tiến triển của bệnh lây lan. Đây không phải là cách chữa trị, mà là một cách để làm cho mèo của bạn thoải mái hơn và kéo dài tuổi thọ của nó thêm vài tháng. Bác sĩ thú y của bạn có thể quyết định loại bỏ chất lỏng tích lũy trog khoang bụng để giảm áp lực. Nếu mèo của bạn mắc FIP, thì thường không có cách điều trị nào là triệt để, vì bệnh lây lan quá nhanh. Tiên lượng tổng thể đối với mèo mắc bệnh là kém. Không có cách điều trị cụ thể nào có vẻ hiệu quả và phần lớn bệnh nhân chết vì biến chứng.",
                    description: "Viêm phúc mạc truyền nhiễm ở mèo (FIP) là một bệnh do virus ở mèo mang tỷ lệ tử vong cao do tính xâm lấn đặc trưng và không phản ứng sốt, cùng với các biến chứng khác. Bệnh này có tỷ lệ tương đối cao xảy ra ở các hộ gia đình nuôi nhiều mèo so với những gia đình chỉ có một con mèo. Rất khó để chẩn đoán, kiểm soát và ngăn ngừa, và trong trường hợp bùng phát trong quá trình mèo sinh sản ở chuồng hoặc lồng mèo, có thể dẫn đến số lượng tử vong cao. Nó thường lây lan qua việc hít phải chất gây ô nhiễm không khí và phân bị nhiễm bệnh, nhưng virus cũng có thể lây truyền qua con người mà đã từng tiếp xúc với chúng, hoặc hoạt động trên các bề mặt đã bị ô nhiễm.")
    Desease.create!(pet_type: 1,
                    name: "Bệnh Chlamydia",
                    symptom: "Nhiễm trùng Chlamydiosis ảnh hưởng đến hệ hô hấp, mắt, hệ tiêu hoá và hệ thống sinh sản của động vật. Mèo có các triệu chứng nhiễm trùng đường hô hấp trên, bao gồm: Hắt xì, chảy nước mắt, có gỉ mắt, ho, khó thở, sổ mũi, chán ăn, sốt, viêm phổi, nếu không được điều trị",
                    reason: "Mèo con có tỉ lệ nhiễm bệnh cao hơn so với các lứa tuổi khác, tuy nhiên tình trạng này có mặt ở mọi lứa tuổi và giống mèo. Mèo được lưu trú trong các khu đông đúc với các động vật khác, như trong khu nội trú, có nguy cơ lây nhiễm cao. Việc lây truyền có thể diễn ra ngay cả khi mèo nhà bạn không tiếp xúc trực tiếp với động vật bị nhiễm bệnh, Vì các vi khuẩn từ việc ho hoặc hắt hơi có thể bám vào người chăm sóc mang vi khuẩn và lây lan nó bằng cách chạm vào, hoặc ôm ấp con mèo khác.",
                    treatment: "Điều trị được tiến hành trên cơ sở ngoại trú tại nhà, bắt đầu với các loại thuốc kháng sinh phổ rộng như tetracycline hoặc doxycycline. Các thuốc kháng sinh có thể được dùng bằng đường uống hoặc là nhỏ trực tiếp vào mắt. Toàn bộ quá trình điều trị có thể mất đến sáu tuần con mèo mới có thể hồi phục.",
                    description: "Nhiễm Chlamydia là một bệnh nhiễm trùng có thể xảy ra ở mèo bị các bệnh về mắt (viêm kết mạc) và các quá trình viêm đường hô hấp trên (viêm mũi, viêm họng, viêm phế quản), trong các trường hợp hiếm hoi hơn hệ thống tình dục bị ảnh hưởng.")
    Desease.create!(pet_type: 1,
                    name: "Bệnh FeLV",
                    symptom: "Thiếu máu, lờ phờ, sụt cân  liên tục, phì đại hạch bạch huyết, tiêu chảy kéo dài, nhiễm trùng tai ngoài và tình trạng da kém, sốt (xảy ra ở khoảng 50% các trường hợp), dáng đi hoặc chuyển động loạng choạng, rời rạc hoặc như say rượu, viêm mũi, giác mạc hoặc các mô ướt của mắt, viêm nướu và/hoặc mô miệng, ung thư hạch bạch huyết  (loại ung thư liên quan đến FeLV phổ biến nhất),sacom xơ (ung thư phát triển từ mô xơ)",
                    reason: "Bệnh bạch cầu ở mèo thường được mắc phải từ việc lây truyền mèo sang mèo (ví dụ: cắn, tiếp xúc gần gũi, chải chuốt và bát thức ăn hoặc khay cát vệ sinh dùng chung). Nó cũng có thể lây truyền sang mèo con khi sinh hoặc qua sữa mẹ. Mèo con dễ bị nhiễm loại virus này hơn, mèo đực và mèo hay đi ra ngoài trời cũng vậy.",
                    treatment: "Bác sĩ thú y sẽ kê thuốc để điều trị các triệu chứng và nguyên nhân gây bệnh bạch cầu ở mèo. Sau đó, nên chủng ngừa các loại virus đường hô hấp và đường ruột hàng năm. Mèo của bạn sẽ không cần nhập viện trừ khi nó bị nhiễm trùng thứ phát nghiêm trọng, số lượng hồng cầu thấp hoặc sụt cân nghiêm trọng kèm theo mất cơ. Trong những trường hợp này, mèo sẽ được giữ lại dưới sự chăm sóc của bệnh viện cho đến khi tình trạng của nó ổn định. Điều trị khẩn cấp, chẳng hạn như truyền máu, đôi khi cần thiết. Nhiễm trùng cơ hội là một mối quan tâm khác. Đây là những bệnh nhiễm trùng xảy ra gián tiếp do hệ thống miễn dịch suy yếu của động vật (do FeLV). Liệu pháp hỗ trợ, chẳng hạn như truyền dịch hoặc thực phẩm bổ sung dinh dưỡng, rất hữu ích trong những trường hợp này. Tiêu chảy, bệnh thận, hoặc mất cơ kéo dài (mãn tính) có thể cần một chế độ ăn uống đặc biệt. Ngoài ra, răng hoặc nướu bị nhiễm trùng phải được làm sạch; cần phải nhổ răng trong trường hợp nghiêm trọng.",
                    description: "Nhiễm virus gây bệnh bạch cầu ở mèo (FeLV) là một bệnh làm suy yếu hệ miễn dịch của mèo và gây ra một số loại ung thư nhất định. Việc nhiễm virus này là nguyên nhân của phần lớn các trường hợp tử vong ở mèo nhà, ảnh hưởng đến tất cả các giống. Mèo đực có nhiều khả năng bị nhiễm bệnh hơn mèo cái, và nó thường xảy ra trong giai đoạn từ một đến sáu tuổi.")
    Desease.create!(pet_type: 1,
                    name: "Bệnh cầu trùng",
                    symptom: "Các triệu chứng chính của bệnh cầu trùng là tiêu chảy phân nước, có dịch nhầy. Tiêu chảy ra máu và không có khả năng kiểm đại tiện sẽ dễ thấy được khi bệnh phát triển, và mèo có thể trở nên yếu ớt và sốt, kèm theo nôn mửa và sụt cân. Mất nước là một vấn đề nghiêm trọng, do tiêu chảy và nôn mửa, và có thể nhanh chóng dẫn đến các biến chứng nghiêm trọng. Hệ thần kinh cũng có thể bị ảnh hưởng, kèm theo run rẩy và bối rối. Các loại cầu trùng lây nhiễm ở mèo: Isospora felis; Isospora rivolta, Sarcocystis, Toxoplasma gondii (lưu ý rằng tình trạng nhiễm cầu trùng này có tính chất kỵ khí), Hepatozoon – được truyền do ăn phải ‘ve chó màu nâu’",
                    reason: "Ở trong môi trường có các động vật bị nhiễm bệnh khác là nguyên nhân phổ biến nhất của loại bệnh này. Nó thường lây lan qua phân phân, nhưng một số loại cũng có thể lây lan qua việc ăn các vật chủ trung gian, chẳng hạn như chuột và chim. Tuy nhiên, thường do một mèo mẹ lây sang con do phân gần nhau và mèo con thường ăn các vật lạ và hay khám phá. Nhiễm cầu trùng đặc biệt nguy hiểm đối với mèo con, vì hệ miễn dịch của chúng vẫn còn chưa phát triển.",
                    treatment: "Phương pháp điều trị thường là ngoại trú. Một loại thuốc có chứa sulfa để tiêu diệt ký sinh trùng sẽ được kê, và thường có tác dụng nhanh và hiệu quả. Mèo sẽ cần được bù nước do tiêu chảy. Nếu mèo bị suy nhược do nhiễm trùng nặng, bác sĩ thú y có thể sẽ cần quan sát trong môi trường y học. Việc kiểm tra theo dõi phân trong vòng 1-2 tuần đầu của quá trình điều trị sẽ là cần thiết để đảm bảo rằng ký sinh trùng không còn tồn tại trong cơ thể nữa. Biện pháp phòng ngừa tốt nhất là cách ly động vật bị nhiễm bệnh. Xét nghiệm ưu tiên phân của mèo trong khi mang thai, hoặc sau khi sinh, để chắc chắn rằng nó không bị nhiễm bệnh sẽ giúp bảo vệ mèo con khỏi bị nhiễm trùng. Chủ nuôi mới có thể cần kiểm tra phân của mèo con để đảm bảo rằng không có cầu trùng, vì đây là một vấn đề phổ biến. Nếu bạn có mèo con bị nhiễm bệnh, hãy báo cho người lại giống hoặc người chủ nôi biết để có thể đưa ra phương pháp điều trị cho các con vật còn lại của họ.",
                    description: "Bệnh cầu trùng là một loại nhiễm trùng ký sinh trùng, gây ra bởi cầu trùng. Bệnh thường gây ra tiêu chảy phân nước, dịch nhầy ở động vật. Nếu không được điều trị, dần dần bệnh có thể gây tổn thương niêm mạc đường ruột của mèo. Với phương pháp điều trị thích hợp và kịp thời, kết quả sẽ rất tốt.")
    Desease.create!(pet_type: 1,
                    name: "Bệnh tiểu đường",
                    symptom: "  - Béo phì, khát nước quá mức, đi tiểu quá nhiều (tăng cả về tần suất và lượng nước tiểu), chán ăn, sụt cân, hao mòn cơ bắp lưng, chi sau yếu, lông có dầu và gàu, gan to, vàng da, lờ phờ                                                                                                                                                                                                                                                       , nhiễm toan ceton, nhiễm toan chuyển hóa do sự phân hủy chất Béo và protein trong Gan để đáp ứng với tình trạng thiếu hụt insulin",
                    reason: " - Di truyền, béo phì, viêm tụy  (pancreatitis), xảy ra đồng thời với một số bệnh: Cường giáp, bệnh Cushing, sử dụng một số loại thuốc",
                    treatment: "Việc kiểm soát bệnh tiểu đường đòi hỏi sự thận trọng và trao đổi thường xuyên giữa bạn và bác sĩ thú y. Bác sĩ sẽ lập một kế hoạch điều trị và kiểm soát riêng cho mèo của bạn dựa trên tình trạng bệnh hiện tại của mèo. Có nhiều loại insulin khác nhau và việc lựa chọn loại phù hợp với mèo của bạn sẽ được thực hiện bởi bác sĩ thú y. Liều lượng insulin sẽ cực kỳ cụ thể và cần phải được cho sử dụng vào cùng một thời điểm mỗi ngày; sự thay đổi trong liều lượng và thời gian có thể dẫn đến tình trạng kiểm soát đường huyết kém hoặc các biến chứng gây nguy hiểm đến tính mạng như nhiễm toan ceton. Sau khi việc điều trị ban đầu đã ổn định tình trạng của mèo, bác sĩ thú y có thể đề nghị cắt bỏ buồng trứng nếu đó là mèo cái, vì các hormone trong suốt thời kỳ động dục có thể khiến việc kiểm soát bệnh tiểu đường trở nên khó khăn.",
                    description: "Tiểu đường là một chứng rối loạn nội tiết do thiếu insulin tuyệt đối hoặc tương đối. Chuyển hóa là cách cơ thể tiêu hóa và sử dụng thức ăn cho việc tăng trưởng và tái tạo năng lượng; quá trình này phụ thuộc phần lớn vào lượng insulin đủ trong cơ thể.")
    Desease.create!(pet_type: 1,
                    name: "Nổi mụn trứng cá",
                    symptom: "Mụn trứng cá ở mèo thường xuất hiện ở trên hay vị trí xung quanh cằm mèo",
                    reason: "Nguyên nhân có thể do căng thẳng và ít được chải chuốt. Hoặc dị ứng với thuốc, tình trạng lớp biểu bì da, hay thậm chí là bát nhựa đựng thức ăn.",
                    treatment: "Bác sĩ thú y của bạn thường khuyên mua một loại dầu tắm hoặc gel đặc hiệu để tẩy rửa sạch những nơi bị mụn. Hơn nữa bạn cũng nên mua thuốc kháng sinh nếu mụn đi kèm với nhiễm khuẩn.",
                    description: "Nổi mụn trứng cá")
    Desease.create!(pet_type: 1,
                    name: "Nhiễm khuẩn",
                    symptom: "Viêm nang lông. ",
                    reason: "Chỗ ở không được vệ sinh thường xuyên",
                    treatment: "Mặc dù có thể dùng thuốc kháng sinh để điều trị nhiễm khuẩn tuy nhiên cần giải quyết hết tất cả những vấn đề về da tiềm. Nhằm ngăn chặn những vấn đề này có thể tái phát.",
                    description: "Trong rất nhiều trường hợp, nhiễm trùng da do vi khuẩn phát triển là một vấn đề khác ở da. Ví dụ như mụn trứng cá ở mèo sẽ làm cho nang lông của mèo dễ bị nhiễm trùng.")
    Desease.create!(pet_type: 1,
                    name: "Nhiễm trùng nấm men",
                    symptom: "Dấu hiệu khi mèo đã bị nhiễm trùng nấm men có thể bao gồm mủ đen hay vàng.Ở tai có những vết đỏ, mèo gãi tai liên tục không dứt.",
                    reason: "Sinh ra do một bệnh khác ở mèo. Tai là một trong những nơi dễ bị nhiễm trùng nấm men nhất trên cơ thể mèo.",
                    treatment: "Sử dụng thuốc kháng nấm là một trong những cách tốt nhất điều trị nhiễm trùng nấm men. Nhưng bạn phải chắc chắn mang mèo cưng đến bác sĩ thú y để chuẩn đoán trước khi sử dụng bất kỳ biện pháp điều trị nào lên mèo.",
                    description: "Nhiễm trùng nấm men được gây ra bởi một loại nấm.")
    Desease.create!(pet_type: 1,
                    name: "Bệnh ecpet mảng tròn",
                    symptom: "Vùng da xung quanh những thương tổn này thường bị bong ra từng mảng và không thể mọc lông. Bệnh ecpect mảng tròn rất dễ lây lan và có thể lây lan ra các vật nuôi khác.  ",
                    reason: "Lây qua mèo hoang hoặc chỗ ở không được vệ sinh thường xuyên.",
                    treatment: "Việc điều trị sẽ phụ thuộc vào mức độ nghiêm trọng của bệnh. Nhưng có thể bao gồm dầu gội đặc trị, thuốc mỡ để bôi, hay thuốc uống.",
                    description: "Ecpet mảng tròn là một loại nấm khác có thể gây tổn thương cho da mèo khi chúng dưới 1 năm tuổi. Căn bệnh này có thể thương tổn trên đầu, tai, và chi trước của mèo")
    Desease.create!(pet_type: 1,
                    name: "Nấm sâu Sporotrichosis",
                    symptom: "Chúng chỉ gây ra những thương tổn nhỏ và cứng, chúng có thể gây rỉ mủ.",
                    reason: "Nấm sâu Sporotrichosis được cho là một mối quan tâm sức khỏe của cộng đồng. Bởi các loại nấm thường hay lây lan từ mèo sang người. Những người có hệ thống miễn dịch yếu thường rất dễ bị nhiễm nấm.",
                    treatment: "Những con mèo bị nhiễm nấm sâu Sporotrichosis cần được điều trị kịp thời. Người chăm sóc mèo phải hết sức cẩn thận và tỉ mỉ vấn đề vệ sinh để tránh lây lan bệnh.",
                    description: "Dù Sporotrichosis – một loại nấm khác hiếm gặp.")
    Desease.create!(pet_type: 1,
                    name: "Viêm da dị ứng",
                    symptom: " Gãi đầu hay cổ là những triệu chứng phổ biến của dị ứng thực phẩm. Các triệu chứng của dị ứng khác bao gồm cắn chân, cắn đuôi hay gãi tai. Dị ứng có thể gây ra rụng lông hay tổn thương da ở bất kỳ chỗ nào trên cơ thể mèo, bao gồm cả bụng.",
                    reason: "Mèo có thể có những phản ứng dị ứng với những sản phẩm chải chuốt làm đẹp, thực phẩm. Đặc biệt là các chất kích thích từ môi trường như phấn hoa hay những vết cắn của bọ chét.",
                    treatment: "Có rất nhiều phương pháp điều trị làm dịu ngứa da do dị ứng. Tuy nhiên, việc tránh tiếp xúc với các chất gây dị ứng vẫn là biện pháp tốt nhất cho vấn đề này.",
                    description: "Viêm da dị ứng")
    Desease.create!(pet_type: 1,
                    name: "Mèo rụng lông từng mảng",
                    symptom: "Nếu bạn sống với mèo, bạn phải học cách đối mặt với việc nhìn thấy lông mèo rụng đầy trên chiếc áo len yêu thích của mình. Tuy nhiên, nếu bạn nhận thấy mèo cưng đang rụng lông nhiều hơn bình thường hay xuất hiện những mảng da không có lông mọc, hãy đến gặp bác sĩ thú y của bạn càng sớm càng tốt. Việc rụng lông bất bình thường có thể là một dấu hiệu cảnh báo một số bệnh tật, cũng như bọ chét, căng thẳng, dị ứng, hay suy dinh dưỡng.",
                    reason: "Mèo có thể có những phản ứng dị ứng với những sản phẩm chải chuốt làm đẹp, thực phẩm. Đặc biệt là các chất kích thích từ môi trường như phấn hoa hay những vết cắn của bọ chét.",
                    treatment: "Có rất nhiều phương pháp điều trị làm dịu ngứa da do dị ứng. Tuy nhiên, việc tránh tiếp xúc với các chất gây dị ứng vẫn là biện pháp tốt nhất cho vấn đề này.",
                    description: "Mèo rụng lông từng mảng")
    Desease.create!(pet_type: 1,
                    name: "Mèo bị bọ chét",
                    symptom: "Các dấu hiệu về những thương tổn về da ở phần vỏ cứng, phần lông mỏng. Điều này chứng tỏ nó đang có dấu hiệu bị bọ chét.",
                    reason: "Lây mèo qua mèo và ở môi trường xung quanh",
                    treatment: "Để diệt trừ bọ chét, bạn sẽ vừa điều trị cho mèo cưng. Đồng thời cũng phải khử sạch nội thất, giường, chăn, nệm. Hãy điều trị bọ chét cho tất cả vật nuôi trong nhà để công việc này đạt hiệu quả tối ưu.",
                    description: "Đây là loại có một loại côn trùng nhỏ bé sống nhờ vào máu mèo. Tuy nhiên, bọ chét là một vấn đề về da rất phổ biến ở mèo. Bạn có thể tìm thấy chúng hay phân của chúng trên bộ lông mèo.")
    Desease.create!(pet_type: 1,
                    name: "Ve tai",
                    symptom: "Dấu hiệu khi mèo bị nhiễm ve tai bao gồm gãi tai quá nhiều, hay lắc đầu, có mùi nồng và một chất thải tối màu từ trong tai mèo. Hãy nghĩ ngay đến ve tai khi cả hai tai mèo đều bị ảnh hưởng.",
                    reason: "Lây mèo qua mèo và ở môi trường xung quanh",
                    treatment: "Bạn có thể điều trị ve tai bằng các sản phẩm chuyên dụng theo chỉ định của bác sĩ thú y.",
                    description: "Ve tai là một loại ký sinh trùng nhỏ thích sống trong sáp và dầu ở bên trong tai mèo. Khi chúng ăn những thứ ở tai mèo. Chúng sẽ gây viêm nhiễm dẫn đến nhiễm trùng da hoặc nhiễm trùng tai rất nghiêm trọng.")
    Desease.create!(pet_type: 1,
                    name: "Rận",
                    symptom: "Một cuộc công phá lớn của rận có thể dẫn đến việc mèo gãi nhiều, thao thức, bồn chồn, những dấu hiệu bất thường ở bộ lông mèo, và rụng lông.",
                    reason: "Lây mèo qua mèo và ở môi trường xung quanh",
                    treatment: "bạn có thể điều trị rận bằng những phương pháp đặc trị.",
                    description: "Rận là một loại ký sinh trùng xuất hiện khi da bị khô. Chúng được tìm thấy ở những con mèo con ít được quan tâm và thường không được chú ý. Cũng giống như ve,  Vì rận là loài chỉ sống trên một số sinh vật nhất định, bạn sẽ không phải lo lắng việc rận sẽ lây từ mèo sang bạn.")
    Desease.create!(pet_type: 1,
                    name: "Lông đuôi thưa",
                    symptom: "rụng nhiều lông đuôi, đuôi ít lông",
                    reason: "Lây mèo qua mèo và ở môi trường xung quanh",
                    treatment: "Việc thiến mèo có thể loại bỏ được vấn đề này ở những con mèo đực. Một vài phương phá điều trị khác bao gồm chăm chải đuôi và sử dụng dầu tắm có công thức đặc trị.",
                    description: " Còn được gọi là tăng sản tuyến ở đuôi, lông đuôi thưa dùng để chỉ những tuyến hoạt động quá mức trên đuôi mèo. Các tuyến này sản xuất ra các chất bài tiết dạng sáp dẫn đến việc rụng lông và những thương tổn cứng giòn. Trong những trường hợp nặng, tình trạng này sẽ khiến cho đuôi dễ bị nhiễm trùng vi khuẩn. ")
    Desease.create!(pet_type: 1,
                    name: "U hạch ái toan",
                    symptom: "Nếu mèo của bạn có những vết loét lan rộng ra hay những thương tổn ở mũi và môi. Nó có thể đang bị một loại phản ứng dị ứng mang tên u hạch ái toan. Phản ứng này có thể xảy ra ở bất cứ khu vực nào trên cơ thể. Nhưng thường gặp nhất ở mặt, miếng đệm lót dưới bàn chân và đùi.",
                    reason: "Đôi khi nguyên nhân của những thương tổn đó có thể là do dị ứng thức ăn hay bọ chét. Tuy nhiên, những tổn thương này có thể dẫn đến việc da mèo bị nhiễm trùng vi khuẩn.",
                    treatment: "Việc điều trị sẽ phụ thuộc vào nguyên nhân gây ra bệnh.",
                    description: "U hạch ái toan")
    Desease.create!(pet_type: 1,
                    name: "U da",
                    symptom: "Một khối u trên da mèo không nhất thiết là dấu hiệu của bệnh ung thư. Tuy nhiên, bạn cũng cần đưa mèo đến bác sĩ thú y để chuẩn đoán bệnh. Những con mèo già và những con mèo có đầu và tai trắng đặc biệt rất dễ bị ung thư da.",
                    reason: "Do gen, môi",
                    treatment: "Để xác nhận một chuẩn đoán cho căn bệnh ung thư, việc sinh thiết là điều nên làm. Nếu đó chỉ là một cái u nhỏ, bác sĩ thú y sẽ khuyên bạn nên cắt bỏ nó hoàn toàn. Đối với những khối u chưa lan rộng, đây có thể là việc điều trị cần thiết duy nhất.",
                    description: "U da")
    Desease.create!(pet_type: 0,
                    name: "Bệnh Parvo",
                    symptom: "Khi virus mới bắt đầu xâm nhập vào cơ thể, chó thường không có bất cứ biểu hiện gì. Sau thời gian nung bệnh khoảng 3-10 ngày, chó cưng mới bắt đầu có các biểu hiện đầu tiên. Nhìn chung, bệnh Parvo ở chó có các biểu hiện khá giống với bệnh Care và tốc độ diễn biến của bệnh cũng nhanh không kém. Các biểu hiện ban đầu có thể kể đến như: mệt mỏi, nôn, bỏ ăn, sốt và những triệu chứng điển hình của mỗi thể bệnh. Dạng viêm cơ tim, dạng đường ruột, dạng viêm ruột kết hợp, chẩn đoán lâm sàng: Chó bị tiêu chảy liên tục. phân có màu hồng hoặc máu và có bốc mùi tanh khắm. chó bị mệt mỏi lừ đừ. chó có bị nôn liên tục, chó đang khỏe mạnh bỗng nhiên ủ rũ, chó bị mất nước, chó bỏ ăn hoặc ăn ít, có thể chẩn đoán bằng test xét nghiệm Parvovirus nhanh để biết kết quả sớm",
                    reason: "Virus gây bệnh Parvo ở chó rất khỏe mạnh. Chúng có thể tồn tại trong môi trường ánh sáng tự nhiên tới 5 tháng, trong bóng tối tới 7 tháng hoặc hơn. Virus có thể lây truyền qua các hình thức trực tiếp và gián tiếp: Lây truyền trực tiếp từ chó ốm sang chó khỏe do tiếp xúc. Nếu tiếp xúc tần suất cao với chó ốm sẽ làm tăng tỉ lệ mắc bệnh. Phân thải chứa virus gây bệnh Parvo ở chó sẽ được côn trùng, chim chóc, hay các sinh vật gặm nhấm phát tán vào môi trường tự nhiên. Người cũng là 1 trung gian truyền bệnh do vuốt ve, ôm ấp chó cưng. Đó là lý do vì sao mà nhiều chú chó hoàn toàn không ra khỏi nhà mà vẫn bị mắc bệnh. Virus lây lan gián tiếp qua thức ăn, nước uống vào đường tiêu hóa của chó. Rồi sau đó xâm nhập vào máu để gây bệnh",
                    treatment: "Hiện nay chưa có thuốc điều trị đặc hiệu. Cách điều trị bệnh Parvo ở chó thường là nâng cao sức đề kháng cho chó. Qua đó giúp chó tạo kháng thể để tự đào thải mầm bệnh. Bệnh Parvo ở chó có thể điều trị được phần lớn là do sức sống, sức chống chọi của chó. Nhưng phần còn lại là do bác sĩ thú y. Bác sĩ sẽ đưa ra 1 phác đồ điều trị phù hợp để giúp chó có thể chống chọi với bệnh. Chỉ cần dùng sai, hoặc quá liều thuốc sẽ có thể dẫn đến tình trạng nguy hiểm cho chó. Chính vì vậy mà bạn không nên tự ý điều trị bệnh Parvo cho chó tại nhà. Parvo virus có tính hướng niêm mạc đường tiêu hóa, gây ra tiêu chảy ra máu với tần suất nhiều. Điều này làm cho nên cơ thể mất nước, mất máu, mất chất cân bằng điện giải rất nhanh. Ta tiến hành bổ sung nước, cân bằng điện giải cho chó bằng cách truyền tĩnh mạch dung dịch ringer lactate, nước muối sinh lý 0,9%, kaliclorid 10%, đường glucose 5 %.. Khi số lượng virus nhân lên đủ mạnh, đủ độc lực làm cho hệ miễn dịch cơ thể suy giảm. Từ đó các vi khuẩn gây hại đường ruột phát triển, nhân lên làm niêm mạc đường tiêu hóa càng bị tổn thương. Lúc này ta tiến hành dùng kháng sinh: ampixilin….để phòng bội nhiễm kế phát. Niêm mạc ruột bị kích ứng bởi các yếu tố gây hại nên gây ra hiện tượng nôn. Ta tiến hành cầm nôn bằng atropin sulphat và đồng thời chú ý tới việc hạ sốt cho con vật. Khi niêm mạc đường tiêu hóa bị tổn thương gây nên bong tróc niêm mạc dẫn đến chảy máu. Từ đó làm cho chó tiêu chảy ra máu hoặc phân lẫn máu. Ta tiến hành cầm máu bằng vitamin k, transami… Kết hợp song song với việc điều trị triệu chứng thì việc nâng cao sức đề kháng cho con vật quan trọng hàng đầu. Nâng cao bằng cách sử dụng các thuốc trợ sức, trợ lực: natri benzoat, cafein, catosal, vitamin….",
                    description: "Bệnh Parvo ở chó lây lan với tốc độ rất nhanh, gây chết nhiều và rất dễ bùng phát thành dịch. Bệnh Parvo hay còn được gọi là bệnh viêm ruột truyền nhiễm ở chó. Đây là 1 loại bệnh truyền nhiễm cấp tính do Canine Parvovirus (CPV) gây nên")
    Desease.create!(pet_type: 0,
                    name: "Bệnh Care",
                    symptom: "Thường là các giống chó ngoại nhập có độ tuổi từ 2 – 12 tháng tuổi. Đặc biệt là chó non khoảng 4 tháng tuổi có tỷ lệ mắc bệnh Care và chết rất cao. Giai đoạn đầu của bệnh Care: Đầu tiên chó sẽ mệt mỏi, ủ rũ, ăn ít hoặc không ăn mà chỉ uống nước. Chảy nước mũi, nước mắt, nôn mửa và không thích vận động. Sau đó chó sẽ sốt 40 – 41,5ºC kéo dài từ 24-26h. Trong giai đoạn này chó có biểu hiện mắt đỏ. Giai đoạn giữa của bệnh Care ở chó: Sau đợt sốt thứ nhất, thân nhiệt chó hạ dần. Chó vẫn có biểu hiện mệt mỏi, ủ rũ nhưng sẽ ăn lại 1 ít. 3-4 ngày sau, các vi khuẩn bội nhiễm bắt đầu gây nên đợt sốt thứ 2 kéo dài khoảng 3-4 ngày. Lúc này bệnh đã trầm trọng hơn. Cùng lúc đó thì chó bắt đầu xuất hiện các biểu hiện về hô hấp, tiêu hóa, da và thần kinh. Giai đoạn cuối của bệnh Care ở chó: Chó bị tiêu chảy cấp, phân có lẫn máu tươi. Niêm mạc ruột bong ra làm cho phân có mùi tanh khắm vô cùng khó chịu và gây bết ở hậu môn. Chó thường bỏ ăn hoàn toàn. Do bị tiêu chảy nên chó mất nước nhanh, mệt mỏi, ủ rũ, đi đứng siêu vẹo hoặc nằm 1 chỗ, bụng hóp, lông xơ xác, không mở mắt nổi do xuất hiện nhiều gèn mắt. Chó thường chết ngay sau 12-14h sau đó. Chó bị bệnh Care từ 10 ngày trở lên thường sẽ có triệu chứng thần kinh. Ở mỗi một giai đoạn chó lại có một biểu hiện và triệu chứng riêng nên khi bạn nghi ngờ rằng chú chó của mình có thể bị nhiễm bệnh Care hay mang ngay tới bệnh viện thú y gần nhất để kiểm tra lâm sàng và xét nghiệm để phát hiện bệnh",
                    reason: " Đường lây truyền của bệnh Care ở chó là qua dịch tiết ở cơ quan, lẫn trong cả không khí mang mầm bệnh. Do chó khỏe tiếp xúc với chó mang bệnh Care. Do chó tiếp xúc với người hoặc các động vật khác mang virus. Ngoài ra, yếu tố thời tiết và môi trường cũng là 1 trong những nguyên nhân khiến cho virus gây bệnh Care ở chó sinh sôi và phát triển mạnh mẽ. Đặc biệt là khoảng thời gian có mưa nhiều và độ ẩm cao.",
                    treatment: " Bệnh Care hiện nay chưa có thuốc đặc trị. Khi phát hiện bị nhiễm bệnh Care ở chó, bạn nên đưa chó đến ngay các cơ sở thú y để điều trị kịp thời. Do đây là 1 bệnh rất nguy hiểm nên tuyệt đối không tự chữa trị cho chó ở nhà. Nguyên lý khi điều trị bệnh Care ở chó là kịp thời bổ sung nước và các chất điện giải đã mất do ỉa chảy. Tăng cường sức đề kháng cho chó và đề phòng nhiễm trùng kế phát. Bổ sung nước và chất điện giải: Cho uống Ozeron 5%, tiếp nước muối sinh lý 0,9% hay đường Gluco 5% vào tĩnh mạch khoeo chó. Cắt nôn: dùng Atropin hay Primeran. Cầm ỉa chảy: Cho uống thuốc đặc trị tiêu chảy chó mèo (ADP), Imudium hay Bisepton 1 lần/ngày. Chống bội nhiễm: Tiêm kháng sinh như Ampicilin, Gentamycine, Streptomycine + Penicilline, Enrofloxacin.. Tăng cường sức đề kháng, trợ sức, trợ lực và cầm máu: Sử dụng các loại thuốc như Spartein, Vitamin C, Vitamin B1, Vitamin B12, Vitamin K…",
                    description: " Đây là 1 trong những loại bệnh nguy hiểm bậc nhất đối với chó. Bệnh Care hay còn gọi là bệnh sài sốt ở chó là 1 bệnh truyền nhiễm cấp tính của loài ăn thịt. Bệnh do 1 loại virus có tên là Canine Distemper Virus – CDV thuộc giống Morbillivirus, họ Paramyxoviridae gây ra. Lây lan rất mạnh với các biểu hiện như: sốt, viêm cata niêm mạc, đặc biệt là niêm mạc đường hô hấp, viêm phổi, nổi mụn ở da và có triệu chứng thần kinh. Virus gây bệnh Care có mặt ở khắp mọi nơi, nên mọi giống chó đều có nguy cơ mắc bệnh.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh Dại",
                    symptom: "Hung dữ khác thường, nước dãi nhiều, giọng sủa khàn, liệt hàm dưới, liệt chi, toàn thân và chết, triệu chứng dại của mèo giống của chó nhưng thích lánh vào chỗ tối, chó dại rất nguy hiểm.",
                    reason: "Virus dại chủ yếu lây truyền qua các vết cắn, vết liếm vào vết thương của một số động vật mắc bệnh dại. Trong một số ít trường hợp, bệnh có thể lây truyền qua đường hô hấp.",
                    treatment: "Tính tới thời điểm hiện tại chưa phương pháp hoặc thuốc điều trị nào cho chó bị bệnh dại. Cách tốt nhất là iêm vacxin phòng dại cho chó theo định kỳ hàng . Hạn chế tiếp xúc với những con vật có biểu hiện bệnh dại",
                    description: "Là một bệnh truyền nhiễm cấp tính nguy hiểm chung giữa động vật và người, gây nên những cái chết với triệu chứng rất thảm khốc. Đặc điểm của bệnh là virút tác động vào hệ thần kinh gây rối loạn thần kinh trung ương là não bộ làm cho con vật trở nên hoãng loạn (điên dại) và chết. Nguồn mang bệnh dại chủ yếu là chó (90%), mèo nuôi (5%) và động vật hoang dã.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh viêm dạ dày và ruột",
                    symptom: "Vài ngày đầu chó ít ăn hoặc bỏ ăn, sốt 39,5 - 40oC, có kèm theo các cơn run rẩy. Sau đó, chó nôn mửa liên tục đồng thời tiêu chảy nặng, phân lúc đầu táo bón sau loãng có màu xám vàng, có lẫn niêm mạc dạ dày và ruột lầy nhầy, có mùi rất tanh. Do nôn mửa và tiêu chảy liên tục, chó mất nước thể hiệûn: mắt trũng, bụng thót, da nhăn nheo. Khi bị mất nước chó không được điều trị kịp thời sẽ chết sau một vài ngày. Thời kỳ cuối của bệnh, chó thường chảy máu ruột nên phân có màu nâu sẫm hoặc lờ đờ như máu cá. Trước khi chết thân nhiệt chó thường hạ thấp . Thời kỳ này chó không đi được, kiệt sức, nằm một chỗ và chết. Bệnh viêm dạ dày và ruột cấp nếu không chữa trị kịp thời, chăm sóc chu đáo thì chó sẽ chết 90 - 100% trong thời gian 2 - 4 ngày. Một số chó qua khỏi nhưng chuyển thành thể viêm dạ dày ruột mãn tính. Thể bệnh này làm chó bị gầy còm, thiếu máu do kém ăn, lúc thì táo bón, lúc thì tiêu chảy.",
                    reason: "Do giun móc (Ancylostoma caninum) : giun móc có những móc nhọn bằng kitin cắm vào vách ruột non ở phần tá tràng, không tràng để hút máu, tạo ra những tổn thương và xuất huyết trong tổ chức niêm mạc ruột. Vi khuẩn có sẵn trong niêm mạc ruột sẽ xâm nhập vào những chỗ bị tổn thương gây thành bệnh viêm ruột cấp. Do virus: Virus Parvo, Virus Carê khi xâm nhập vào hệ thống tiêu hóa của chó phát triển nhanh chóng, phá hoại niêm mạc dạ dày và ruột. Do vi khuẩn : Chó ăn uống phải thức ăn và nước uống có chứa vi khuẩn thương hàn (Salmonella), vi khuẩn yếm khí (Clostridium), vi khuẩn E.Coli... Những vi khuẩn này sẽ phát triển trong niêm mạc đường tiêu hóa gây ra bệnh viêm dạ dày và ruột cấp.",
                    treatment: "Nguyên tắc chung là chẩn đoán đúng nguyên nhân gây bệnh từ đó điều trị nguyên nhân kết hợp với điều trị triệu chứng, trợ sức và trợ tim mạch. Điều trị bằng một trong các loại kháng sinh sau: Spectylo : liều 1ml/ 3 - 5 kg thể trọng. Tylenro 5 + 5 : liều 1ml/10kg thể trọng/ngày. Kết hợp với điều trị triệu chứng và bồi dưỡng bằng các loại như : Vime C : liều 500mg/con/ngày, Vitamin B6 : liều 1ml/con/ngày,vitaral : liều 1ml/10kgP, Paravet : liều 1ml/4 kgP, Atropin : liều 2ml/10 -15 kgP, Na.campho : liều 2 - 4 ml/con/ngày. Truyền glucose 5% để cung cấp nước và chất điện giải giúp chó mau hồi phục.",
                    description: "Bệnh phổ biến xảy ra quanh năm thường thấy nhiều vào mùa hè khi thời tiết nóng và mưa ẩm ướt. Có 3 nguyên nhân có thể gây ra viêm dạ dày và ruột cấp ở chó.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh viêm phế quản",
                    symptom: "Do chất kích thích vào đường hô hấp, tác động đến thần kinh gây ho và nếu tác động lâu sẽ sinh bệnh viêm, niêm mạc sưng do viêm hoặc sung huyết sẽ làm hẹp đường hô hấp. Các chất phân tiết bịt kín đường thông khí làm chó khó thở. Những biểu hiệu đặc trưng nhất là: Vật bị ho, khó thở, nhất là vào buổi sáng, lúc dầu ho khan sau trở thành ướt và kéo dài. Thở khò khè, có tiếng ran, chảy nươc mắt, nước mũi liên tục. Có thể kèm theo sốt: 39,5-40,50C,. mệt mỏi, bỏ ăn. Viêm phế quản mãn tính thường không sốt nhưng ho kéo dài, có lúc ho ra đờm nhầy.",
                    reason: " - Do bị nhiễm cùng lúc nhiều laọi vi khuẩn gây bệnh đường hô hấp như: Liên cầu (streptococcus), tụ cầu (staphylococcus aureus), klebsiella pneumoniae, bordetella bronchiseptica, thường do kế phát của một số bệnh nhiễm trung như care, viêm ruột, bệnh ký sinh trùng. Do thời tiết và vệ sinh môi trường, hít phải khói bụi, hoá chất gây kích thích đường hô hấp. Do thức ăn, nước uống sắc xuống đường hô hấp.",
                    treatment: "Nguyên tắc chung: Dùng kháng sinh diệt nguyên nhân gây bệnh, thuốc chữa triệu chứng, thuốc bổ trợ. Dùng một trong các loại kháng sinh sau đây: Penicilin: tiêm bắp liều 300-500.000UI/ngày, chia 2-3 lần trong ngày. Gentamycin: Tiêm bắp liều 8-10 mg/kg thể trọng, chia 2lần trong ngày. Stretomycin: Tiêm bắp liều 20-25mg/kg thể trọng, chia 2 lần trong ngày. Hiện nay trên thị trường thuốc thú y có mọt số biệt dược sử dụng điều trị viêm phế quản ở chó: Cefa.Doc: Thành phần gồm: Cefalexine. Liodocaine HCl và dung môi. Tiêm bắp liều 1ml/5kg thể trọng. Cefadox.T: Thành phần gồm cefalextine, Doxycylin, Sulfadiazine, Trimethoprime và B. Complex. Thuôc bột hoà nước cho uống, liều 1g/5kg thể trọng. Kanacolin: Thành phần gồm Kanamycin sulfate và Ampiciline sodium. Tiêm bắp liều 1mg/5kg thể trọng. Thuốc chữa triệu chứng: Ephedrin: Thuốc giảm ho, chống khó thở. Tiêm bắp 1-2 ông x 1mg/ngày. Dimedron: Giảm ho, an thần. Tiêm bắp 1-2 ống X1ml/ngày. Thuốc trợ sức: Cafein 5%: tiêm bắp 3-6ml/con. Vitamin B1 25%, tiêm bắp 3-5ml/con. Vitamin C 5% tiêm bắp 3-5ml/con. Glucoza 30% tiêm bắp 5ml/con. Truyền huyết thanh mặn đẳng trương (trong những trường hợp chó yếu).",
                    description: "Bệnh viêm phế quả là bệnh viêm mạc đường hô hấp, viêm phế quản hay phế quản nhỏ sau đó dẫn dến khí quản , nặng hơn dẫn đến viêm phổi. Bệnh này xảy ra ở chó, khi thời tiết thay đỏi từ ấm áp sang lạnh ẩm, thường từ cuối thu sang đông và đến đầu mùa xuân.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh viêm phổi",
                    symptom: "Thoạt đầu mới nhiễm bệnh, con vật mệt mỏi, uể oải, bỏ ăn, sốt cao, niêm mạc đỏ. Tuy ít ho nhưng khó khăn, đau đớn, cơn ho khạc cũng tăng dần lên ngày một nặng, cơn ho xảy ra nhiều vào ban đêm và sáng sớm. Thở khó, con vật nằm một chỗ, yếu, cố thở nhanh và nông, biểu hiện thiếu oxy trong máu nên niêm mạc mắt, miệng đỏ xẫm, sung huyết, sau tím tái. Nếu không điều trị kịp thời, con vật sẽ chết sau vài ngày vì khó thở và suy kiệt.",
                    reason: "Thường do nhiễm virut đường hô hấp, sau đó là kế nhiễm vi khuẩn như các loại vi khuẩn: Pneumococcus, Streptococcus, Klebsiella, Bordesella…. Do một số loại ấu trùng của ký sinh trùng ở phế quản như Filaroides, Actustrongylus, Paragonimus cũng gây viêm phổi. Do một số nấm như Asperrgillus, Histoplasnia. Lúc đầu do tác động của virut xâm nhập qua đường hô hấp gây viêm vách phế quản nhỏ, sau lan đến nhu mô phổi hoặc có thể qua đường tuần hoàn làm cho tổ chức phổi yếu đi. Trên cơ sở đó các vi khuẩn có sẵn ở đường hô hấp sẽ phát triển và gây bệnh viêm phổi, nặng hơn gây hoại thư hoặc sinh mủ trong tổ chức phổi.",
                    treatment: "Cũng theo nguyên tắc chung. Sử dụng thuốc kháng sinh chữa nguyên nhân.Thuốc chữa triệu chứng. Thuốc trợ sức và hộ lý. Sử dụng một trong các loại kháng sinh sau đây: Penicilin G: Tiêm bắp cho chó liều 500.000 UI/ngày, cho mèo liều 200.000 UI/ngày, chia 2-3 lần trong ngày. Streptomycin: Chó 1g/ngày, mèo 500mg/ngày. Tiêm bắp, chia 2-3 lần trong ngày. Thường nên phối hợp Penicilin với streptomycin thì hiệu quả chữa bệnh viêm phổi tốt nên rất nhiều. Kanamycin: Tiêm bắp liều 40mg/kg thể trọng/ngày, chia 2-3 lần trong ngày. Erythromcycin: Tiêm bắp thịt, liều 20-25 mg/kg thể trọng/ngày. Chia 2 lần trong ngày. Erythromcycin hiệu lực cao với bệnh viêm phổi nhưng với chó, mèo có thể có tác dụng phụ như nôn mửa, rối loạn tiêu hóa, nhưng sau ít ngày sẽ hết. Theo kinh nghiệm của các nhà điều trị: Nên phối hợp kháng sinh tiêm với Trimazon (Bisepton) cho chó uống với liều 40mg/kg thể trọng/ngày. Kết quả chữa bệnh sẽ tốt hơn. Thuốc chữa triệu chứng: Giảm ho dễ thở: Ephedrin tiêm bắp 1-2 ống x 1ml/ngày. Ngày tiêm 1-2 lần. An thần, giảm sốt, giảm đau: Dimedron tiêm bắp 0,5-1 ống x 1ml/ngày. Ngày tiêm 1-2 lần. Hoặc Promix 1ml/5kg thể trọng. Thuốc trợ tim, trợ sức. Truyền Ringerlactat liều 100-150 ml/kg thể trọng/ngày. Cafein 5%: Tiêm bắp 3-5ml/con, ngày 2 lần. Vitamin B1 2,5%: Tiêm bắp 3-5ml/con, ngày 2 lần. Vitamin C 5%: Tiêm bắp 3-5ml/con, ngày 2 lần. Glucoza 30%: Tiêm tĩnh mạch, liều 5ml/con. Hộ lý: Chăm sóc và nuôi dưỡng chu đáo.",
                    description: "Bệnh viêm phổi thường là kế phát của viêm phế quản hay do bội nhiễm từ các bệnh truyền nhiễm khác như bệnh carê; viêm phế khí quản truyền nhiễm ở chó.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh viêm tử cung",
                    symptom: "Chảy dịch từ âm đạo, biếng ăn, uống nhiều nước, bụng trương to, sốt, ói mửa, tiêu chảy",
                    reason: "Do hậu quả của quá trình sinh đẻ, sót nhau, sảy thai, thai chết, máu và dịch thẩm xuất tích lại trong tử cung, âm đạo chó tạo điều kiện cho vi khuẩn từ cổ tử cung xâm nhập vào gây bệnh. Các vi khuẩn thường gặp là tụ cầu khuẩn Staphylococcus, liên cầu khuẩn Streptococcus, E. coli dung huyết và Klebsiella.",
                    treatment: "Theo nguyên tắc chung là điều trị nguyên nhân kết hợp điều trị triệu chứng, kết hợp với các thuốc bổ trợ và chăm sóc, nuôi dưỡng chu đáo nhằm tăng cường sức đề kháng của cơ thể. Thụt rửa tử cung, âm đạo bằng dung dịch Rivanol 0,1% hay thuốc tím 0,1%, mỗi ngày thụt rửa một lần, trong 3 – 5 ngày. Chống nhiễm khuẩn: sử dụng một trong các thuốc kháng sinh sau đây: Có thể dùng Penicillin, Ampicillin: tiêm bắp liều 10.000 UI/kg thể trọng/ngày, Kanamycin: tiêm bắp liều 10 mg/kg thể trọng/ngày. Điều trị liên tục trong 5 – 7 ngày. Điều trị viêm âm đạo do nhiễm khuẩn và nhiễm nấm. Sử dụng một trong các loại thuốc kháng sinh chống nhiễm khuẩn giới thiệu ở trên kết hợp với thuốc đặc trị trùng roi và nấm: Klion: hòa nước cho uống, liều 10mg/kg/ngày. Điều trị liên tục 5 – 7 ngày. Ketomycin: chó 1 – 2 g/con, mèo 0,5 – 1 g/con, hòa nước sạch hay nước cháo cho uống. Điều trị liên tục trong 5 – 7 ngày. Dearnewtab: đặt vào âm đạo 1 viên/ lần, ngày đặt 2 lần, với mèo đặt 1/2 viên/ngày. Flagystine: 1 viên/lần/ngày đặt sâu vào tử cung. Metronidazole, Nystatine, Dexamethasone: đặt sâu vào tử cung, chó 1 viên/lần/ngày, mèo 1/2 viên/lần/ngày. Cần ngâm viên thuốc vào nước khoảng 30 giây trước khi đặt. Thuốc chữa triệu chứng: cầm máu bằng vitamin K, hồi phục tổ chức niêm mạc tử cung, âm đạo: tiêm vitamin A, D, E. Chống kích ứng niêm mạc và chống co thắt tử cung, âm đạo: tiêm bắp Atropin 1% hay Primeran liều 1-2ml/con/ngày. Trợ sức, trợ lực bằng cách tiêm vitamin B1 2,5%, vitamin C 5%, B. complex. Truyền dung dịch mặn – ngọt đẳng trương 15 – 20 ml/kg thể trọng/ngày. Truyền 2 – 3 ngày.",
                    description: "Tỷ lệ phát hiện bệnh viêm tử cung giữa khám lâm sàng so với kỹ thuật siêu âm chiếm tỷ lệ khá cao là 68,74%. Bệnh viêm tử cung ở chó cái có một số biểu hiện lâm sàng đặc trưng dễ phát hiện, điều này rất có ý nghĩa đối với những cơ sở điều trị chưa được trang bị máy siêu âm. Tuy nhiên có một số chó bị viêm tử cung nhẹ chưa có biểu hiện lâm sàng đặc trưng thì khó phát hiện bằng cách khám lâm sàng. Theo nghiên cứu thì tỷ lệ mắc bệnh viêm tử cung ở nhóm chó ngoại cao hơn nhóm chó nội. Lí do có lẽ tỷ lệ bệnh cao ở nhóm chó ngoại là do những chó ngoại phần lớn có giá trị kinhh tế cao, thường được nuôi nhốt trong căn hộ, được người nuôi quan tâm nhiều hơn và dễ phát hiên bệnh.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh mò bao lông",
                    symptom: "Bệnh ghẻ mò bao lông thường phát sinh ở phía trước mắt, hoặc khủy chân. Bệnh có thể thay đổi từ rất nhẹ như chỉ một mảng nhỏ, cho đến nặng như toàn thân đều có bệnh tích rướm máu, có mủ. Với trường hợp bệnh nhẹ thì có thể chỉ bị một khu vực tách biệt, bị rụng lông ở mặt, quanh mắt hay chân trước hoặc cả chân sau. Những trường hợp này được xem là bệnh nhẹ, không gây viêm da thứ phát. Còn trường hợp nặng thì da bị mẫn đỏ lên, có mụn mủ, có máu và huyết thanh rỉ ra từ những vùng nhiễm bệnh, kế đó là nhiễm trùng thứ phát mà thường thấy là Staphylococcus aureus, thỉnh thoảng cũng thấy Pseudomonas spp",
                    reason: "Chỗ ở không được vệ sinh sạch sẽ, tiếp xúc trực tiếp với các chó bị bệnh.",
                    treatment: "Ký sinh trùng: Khi bệnh khu trú có giới hạn thì thường tự khỏi, tuy nhiên để đề phòng bệnh lan ra toàn thân ta nên điều trị sớm ở những trường hợp này bằng: Amitra với nồng độ 0,025% trong nước, mỗi tuần bôi một lần, cho đến khi dứt các bệnh tích, rồi tiếp tục bôi mỗi hai tuần một lần, cho đến khi xét nghiệm không còn ký sinh trùng. Rotenone (C23H22O6) 1% pha trong cồn bôi trong ba ngày liên tục, Benzyl benzoat, Trypanbleu. Tẩm bằng các xà bông sát trùng. Trị nhiễm trùng thứ phát với : chloramphenicol, lincomycin.",
                    description: "Bệnh mò bao lông do một ký sinh trùng da sống trong nang lông gây ra ngứa ở các mức độ khác nhau. Bệnh ở chó phổ biến hơn ở mèo")
    Desease.create!(pet_type: 0,
                    name: "Bệnh ve kí sinh",
                    symptom: "Ve thường bám ở trong và ngoài vành tai, vùng cổ và ở kẻ ngón chân. Nhiễm nặng thì thấy ve bám khắp cơ thể, có khi hàng ngàn ve trên một ký chủ, gây tổn thương sinh ra phản ứng viêm, làm chó ngứa ngày khó chịu, gãi thường xuyên có thể tạo nhiễm trùng thứ phá, áp xe hay loét. Nếu nhiều thì làm cho ký chủ bị thiếu máu, một số chỗ của da xù xì, dày lên, chó cứ gậm, liếm, cào cấu thường xuyên. Khi loại trừ được ve thì các triệu chứng trên giảm ngay. Nguy hiểm nhất là ve truyền các bệnh truyền nhiễm như: rickettsia, leptospirosis, babesiosis.",
                    reason: "Chỗ ở không được vệ sinh sạch sẽ, tiếp xúc trực tiếp với các chó bị bệnh",
                    treatment: "Các loại thuốc có thể dùng điều trị như: Frontline với các hoạt chất fipronil xịt và xoa lên lông chó, mèo, mỗi lần trừ ve được một tháng. Bayticol (flumethrin 6%) pha 1ml cho 2 lít nước tắm hay xịt cho chó. Vòng đeo cổ Preventef (diazenon) trừ được ve trong 4 tháng. Phòng Bệnh: Để kiểm soát ve ta có thể định kỳ xịt thuốc sát trùng vào chỗ ở của chó như chuồng, góc nhà, vách tường, kẻ tường, sân. Nhưng phải tách người và thú vật ra khỏi khu vực này cho đến khi thuốc hết tác dụng. Dùng vòng đeo trừ ve.",
                    description: "Ve là một loại ký sinh trên chó, nó không chỉ tranh chấp chất dinh dưỡng của ký chủ mà còn truyền một số bệnh nguy hiểm cho chó.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh rận kí sinh",
                    symptom: "Trước hết rận bò trên da làm con vật ngứa ngáy không nghỉ ngơi được. Nhiễm rận nhiều gây kém ăn, chậm lớn, vết đốt gây viêm biểu bì, bao lông, gây ngứa ngáy, rụng lông lỗ chỗ. Rận ăn lông Trichodectes còn là ký chủ trung gian cho sán dây Dipylidium caninum.",
                    reason: "Chỗ ở không được vệ sinh sạch sẽ, tiếp xúc trực tiếp với các chó bị bệnh",
                    treatment: "Các loại thuốc có thể dùng điều trị như: Bayticol (flumethrin 6%) pha 1ml cho 2 lít nước tắm hay xịt cho chó. Để tiêu diệt mầm bệnh ta có thể lập lại sau 14 ngày",
                    description: "Rận ký sinh ở chó phổ biến có 2 loại: Rận ăn lông và Rân hút máu. Rận ăn lông: gồm các loại như: Trichodectes canis, Trichodectes latus Heterodoxus spiniger, các loại này không hút máu chỉ ăn lông. Vòng đời chỉ trãi qua trên ký chủ, con cái đẻ trứng, màu trắng đầu có nắp dính trên lông ký chủ, 5-12 ngày nở thành ấu trùng rồi lột xác 3 lần trong 12-16 ngày để trở thành con trưởng thành. Rận hút máu: Phổ biến là Linognathus selosus, rận đẻ trứng trên lông, trứng nở ra thiếu trùng và qua 3 lần lột xác thành con trưởng thành, toàn bộ vòng đời mất 2-3 tuần.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh bọ chét kí sinh",
                    symptom: "Thấy dễ dàng ở vùng không lông hay ít lông như bụng, háng. Gây cho ký chủ ngứa ngáy, viêm da, mụn loét, rụng lông. Nguy hiểm nhất là truyền những bệnh khác như: sán dây Dipyllidium caninum, vi trùng bệnh dịch hạch.",
                    reason: "Chỗ ở không được vệ sinh sạch sẽ, tiếp xúc trực tiếp với các chó bị bệnh",
                    treatment: "Các loại thuốc có thể dùng điều trị như: Dipterex 0.3-0.5 %. Bayticol (flumethrin 6%) pha 1ml cho 2 lít nước tắm hay xịt cho chó. Vòng đeo cổ Preventef (diazenon) trừ được bọ chét trong 4 tháng. Frontline với hoạt chất fipronil xịt và xoa lên lông chó trừ được bọ chét 2 tháng. Program (lufenuron) mỗi tháng một viên. Về sức khỏe cộng đồng: Trẻ em có thể nhiễm sán dây Dipylidium caninum mà nguyên nhân là do nuốt phải bọ chét mang ấu trùng sán dây.",
                    description: "Đây là một loại ký sinh trùng ngoài rất phổ biến ở chó, bọ chét không gây hại nặng trực tiếp nhưng lây lan rất nhanh và khó tiêu diệt mầm bệnh.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh giun ở mắt ",
                    symptom: "Viêm kết mạc và tiết rất nhiều nước mắt, sợ ánh sáng. Trong trường hợp nhiễm nặng có thể gây loét và đục giác mạc. Giun trưởng thành có thể tìm thấy trong túi kết mạc và ấu trùng thường có trong nước mắt.",
                    reason: "Ruồi nhà Musca domestica, Fannia sp và ruồi Musca autumnalis là những ký chủ trung gian. Từ chó bệnh được ruồi ăn chất tiết của mắt có ấu trùng L1, vào cơ thể ruồi ấu trùng phát triển thành L3 và di hành đến miệng ruồi để sẵn sàng truyền cho chó khác khi ruồi đậu vào mắt. Từ đây ký sinh trùng trực tiếp phát triển thành con trưởng thành, giun có thể sống trong mắt vài ba năm, giun non có biểu bì hình răng cưa và di chuyển nhanh trong mắt ký chủ gây ra viêm kết mạc.",
                    treatment: "Có thể trị bằng các phương pháp sau. Trực tiếp lấy giun ra khỏi mắt. Nhỏ dung dịch levamisole 2% vào giác mạc. Dùng thuốc mỡ tra mắt levamisole 1%.",
                    description: "Bệnh giun ở mắt chó thường gây ra do hai loài Thelazia californiensis và T. callipaeda, chúng thường ký sinh trong túi giác mạc hay trong giác mạc của chó, giun có thể tìm thấy ký sinh ở trên mắt người. Ngoài ra bệnh có thể xảy ra ở những loài khác. Giun có lớp biểu bì hình răng cưa, dài khoảng 10-15 mm.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh viêm miệng do nấm",
                    symptom: "Bệnh biểu hiện đặc trưng bởi những vãy trắng, hay màng giả trên niêm mạc miệng hay lưỡi, đôi khi lan cả đến môi, bệnh tích thường nổi lên với sự sung huyết ở xung quanh và bên ngoài còn ở dưới thì lóet, những bệnh tích này có thể lan tràn đến hầu hoặc thực quản. Bệnh làm cho con vật đau. Có thể phân lập định danh nấm C. albican từ những bệnh tích.",
                    reason: "Nguyên nhân gây bệnh là do nấm men Candida albican. Bệnh thường xảy ra ở chó, mèo non hoặc ở những con lớn tuổi. Những điều kiện khác thường là do dùng kháng sinh kéo dài, cơ thể suy giảm miễn dịch, suy nhược, làm biến đổi hệ vi khuẩn trong xoang miệng là nhnữg điều kiện cho nấm phát sinh bệnh.",
                    treatment: "Nên phân biệt với những bệnh gây viêm lóet khác. Các thuốc có thể dùng là: Ketoconazole 10 mg/kg, cho uống ngày 2 lần cho đến khi bệnh khỏi. Bôi potassium permanganate 1/3000 trong nước ngày một lần. Bôi dung dịch nystatin ngày bốn lần. Cố gắng cho chó ăn thức ăn lỏng dễ tiêu để chó dễ nuốt, và bổ sung các vitamine A, B, C trong khẩu phần.",
                    description: "Là một bệnh nhiễm trùng của xoang miệng, bệnh này không phổ biến lắm.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh ca rê",
                    symptom: "Xảy ra ở tất cả các lứa tuổi nhưng thường ở chó con vài tuần tới 12 tháng tuổi. Chó bắt đầu bệnh sốt 40o - 40,5o, chó ủ rũ bỏ ăn, sau 24 - 48 giờ thì hạ sốt, ăn lại. Vài ngày sau lại bỏ ăn, sốt, bệnh tiến triển trầm trọng. Chó bệnh thường hay trải qua hai đợt sốt nên người ta còn gọi là dạng sốt hai thì. Vì virus thường tác hại chính trên đường tiêu hóa và hô hấp nên chó bị tiêu chảy có máu, cũng như viêm đường hô hấp, ho vớiï dịch tiết mũi có mũ. Một số trường hợp khá phổ biến chó bệnh có mụn mũ ở vùng da mỏng như bụng, háng, với diển tiến lúc đầu viêm đỏ sau thành mũ rồi vở ra khô lại. Ở những trường hợp bệnh nặng người ta thấy chó thể hiện triệu chứng thần kinh như co giật, run từng cơn, hoặc hai chân trước giật từng hồi như bơi trong không khí. Mỗi trường hợp có một dạng co giật khác nhau, giai đoạn cuối chó bị liệt. Hầu hết chó xuất hiện dạng thần kinh thường chết. Một số ít có thể vượt qua được thì mang di chứng thần kinh. Một số trường hợp khác thì thể hiện triệu chứng gan bàn chân dầy và cứng, khi ta sờ tay vào cảm giác rất nhám. Đôi khi cũng xảy ra hiện tượng dày và cứng mũi.",
                    reason: "Bệnh do virus thuộc nhóm paramyxovirus. Virus xâm nhập vào chó qua đường hô hấp, tiêu hóa, da. Đầu tiên khi xâm nhập vào virus nhân lên ở mô bạch huyết đường hô hấp trên, sau đó nhiễm vào máu và virus tiếp tục nhân lên ở mô bạch huyết của các cơ quan khác. Mầm bệnh được thải ra qua dịch tiếït mắt mũi, nước bọt, phân, nước tiểu.",
                    treatment: "Nguyên tắc điều trị là giới hạn sự nhiễm trùng thứ phát, truyền dịch tạo lại cân bằng điện giải, giới hạn những cơn co giật và chăm sóc cẩn thận. Giữ chó bệnh ở nơi khô ấm, thuốc hạ sốt, thuốc giảm đau, atropine dể giới hạn co thắt ruột. Dùng kháng sinh hoạt phổ rộng để chống nhiễm trùng thứ phát. Trimethoprim + sulphamethoxazole. Streptomycine 5-10 mg/kg, ngày hai lần tiêm thịt hay dưới da. Gentamicin 2mg/kg ngày 2 lần dùng tối đa 5 ngày. Kanamycin 10-20 mg/kg ngày bốn lần cho uống, hoặc 5-7,5 mg/kg ngày hai lần tiêm thịt hoặc dưới da. Truyền dịch: dung dịch điện giải, dung dịch protein, và thuốc chống co giật.",
                    description: "Bệnh ca rê gây tác hại trên nhiều hệ nhưng trên hệ tiêu hóa là nặng nhất và rõ nhất. Đây là một trong những bệnh nguy hiểm và phổ biến nhất của chó. Bệnh xảy ra trên hầu khắp thế giới, giết hại rất nhiều chó không được tiêm phòng. Bệnh có thể xảy ra trên tất cả các lứa tuổi chó nhưng tác hại nặng trên chó con. Các cơ quan bị virus tấn công nhiều nhất là hệ tiêu hóa, hô hấp, da, thần kinh.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh sốt co giật Canxi ở chó mẹ nuôi con",
                    symptom: " - Bệnh sốt giật can-xi thường gặp ở những chó mẹ sữa tốt, rất ham và quấn con, khéo chăm con, nuôi nhiều con và đàn con rất mập (gọi là bụ sữa). Hoặc đàn con quá lớn (trên 2 tháng tuổi) vẫn để bú mẹ. Tổng trọng lượng chó con lớn hơn 30% trọng lượng chó mẹ, có trường hợp còn nặng hơn cả chó mẹ. Vì thế trong đàn chó nuôi tự nhiên, để tự bảo vệ mình, chó mẹ thường phải chạy trốn chó con bằng cách nhảy lên chỗ cao, chó con không bú được. Ngày xưa chắc các cụ cũng chứng kiến nhiều bệnh này nên dân gian có câutrốn như chó trốn con để ám chỉ những người mẹ không tốt!!! Phân biệt với các triệu chứng thần kinh co giật của các bệnh sau: Bệnh Carre:phải có thời gian ủ bệnh, bệnh diễn biến chậm, không sốt cao, có lây lan sang chó khác ở mọi lứa tuổi. Bệnh uốn ván: phải có vết thương, người cứng như gỗ, hàm cứng. Bệnh Dại: Sợ ánh sáng, phải có vết cắn của động vật mắc Dại, chạy nhảy lung tung, người mềm, không khó thở, tấn công người và súc vật khác...",
                    reason: "Việc chó con bú rút lượng sữa quá lớn tại một thời điểm làm cho nồng độ can-xi huyết tụt dưới 8,0 mg/ml gây ra mất cân bằng can-xi ( tụt can-xi ), rối loạn hoạt động thần kinh trung ương, trung khu điều hòa thân nhiệt và hệ hô hấp, tuần hoàn và vận động. Xin lưu ý: đây không phải là bệnh thiếu can-xi như thường xảy ra với chó non dưới 6 tháng tuổi do thiếu ánh nắng và vận động ít, là bệnh mạn tính.",
                    treatment: " - Cách ly ngay với chó con. Hạ nhiệt gấp bằng tắm nước hoặc chườm nước lạnh. Mời BS Thú Y ngay, khẩn trương tiêm tĩnh mạch Canci Chloride 10% (500mg/ống 5ml). Chó < 5kg tiêm 1-2 ml. Chó 5-10kg tiêm từ 3-5 ml, chó lớn>10kg tiêm từ 5-8ml. Chú ý: Tiêm chậm vào tĩnh mạch, không tiêm bắp thịt hoặc để thuốc ra ngoài mạch gây hoại tử, thối thịt. Sau 4-6 giờ tiêm lại lần 2. Sau khi tiêm Canci Chloride chó mẹ đỡ ngay các triệu chứng, dễ chịu, có thể truyền dung dịch đường Glucose 5-10% , hoặc dung dịch truyền Lactated Ringer (nước biển)vào tĩnh mạch.",
                    description: "Sốt giật can xi rất hay xảy ra với chó mẹ sau đẻ từ 15 ngày trở ra, cũng có trường hợp bị chỉ vài ngày sau khi sinh. Nồng độ can-xi máu trung bình của chó từ 8,4-11,2 mg/ml. Do đột xuất do chó con bú quá mức, hệ thống tiết sữa cơ thể chó mẹ phải tăng tốc quá tải, lượng Can-xi trong máu bị mất cân bằng đột ngột dưới 8,0 mg/ml máu. Bệnh xảy ra nhanh, các biện pháp bổ sung can-xi trong kỳ tiết sữa cho chó mẹ đều không hiệu quả phòng bệnh.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh Lyme",
                    symptom: "Triệu chứng số một là nhịp nhàng ở các chi có thể chuyển từ chân sang chân trong một khoảng thời gian. Độ cứng và sự thèm ăn cũng có thể xảy ra.",
                    reason: "Do bọ chét ký sinh gây nên",
                    treatment: "Điều trị là thông qua kháng sinh và mặc dù các triệu chứng thường được giải quyết trong 4 tuần, chúng có thể không phải lúc nào cũng biến mất. Giữ cho con chó của bạn tránh xa các vùng dễ bị đánh dấu và kiểm tra chó của bạn cho ve luôn luôn là những ý tưởng tốt, nhưng các loại thuốc đánh dấu ngăn ngừa là cách hiệu quả nhất để ngăn ngừa bệnh Lyme và các bệnh khác do bọ chét gây ra. Có những loại thuốc theo chủ đề để đẩy lùi và giết những con ve mà bạn đặt trực tiếp vào lông thú của bạn, như Frontline và K9 Advantix. Ngoài ra còn có thuốc viên, như NexGard , và thậm chí collars con chó của bạn có thể mặc, như Preventic . Chỉ cần ghi nhớ hiệu quả của các loại thuốc tại chỗ giảm qua tháng, đặc biệt là nếu con chó của bạn đi bơi hoặc có một bồn tắm. Phòng ngừa trong năm là tốt nhất.",
                    description: "Bệnh tật do bọ chét này là một bệnh có thể phòng ngừa cao khác. Đó là do một vi khuẩn truyền qua các con hươu hươu ăn chậm đã được gắn vào con chó trong ít nhất 18 giờ. Đó là bệnh phổ biến nhất trong số các bệnh liên quan đến đánh dấu.")
    Desease.create!(pet_type: 0,
                    name: "Ngộ độc Chocolate",
                    symptom: "Các triệu chứng ngộ độc sô cô la bao gồm nôn mửa, tiêu chảy, nhịp thở, thở hổn hển, và lắc. Các trường hợp nghiêm trọng hơn có thể gây nhịp tim bất thường, động kinh, cơn đau tim, hoặc thậm chí tử vong.",
                    reason: "Ăn sô-cô-la đen hoặc chocolate sữa",
                    treatment: "Con chó của bạn nên được nhìn thấy ngay lập tức. Đừng cố làm nôn mửa ở nhà. Hãy mang bác sĩ thú y ngay lập tức",
                    description: "Rất nhiều người đều biết rằng chó không thể ăn sô cô la. Nhưng đáng ngạc nhiên, một số lượng lớn con chó vẫn có thể nắm bắt được nó, và nó vẫn là nguyên nhân phổ biến nhất gây ngộ độc ở chó.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh viêm gan",
                    symptom: "Tăng nhiệt độ trực tràng (39,4°C đến 41,1°C), tăng tần số hô hấp. Sốt có thể không còn. Sưng hạch amidan thường kết hợp với viêm họng và viêm thanh quản, ho và có âm khan trên đường hô hấp. Thường thấy các nốt bạch huyết trên cổ lớn lên gây phù nề dưới da đầu và cổ. Đau bụng và gan thường rõ ràng trong các ca bệnh viêm gan ở chó cấp. Đốm xuất huyết và các vết bầm lan rộng dưới da, chảy máu cam và chảy máu tĩnh mạch cũng thường xảy ra. Vàng da không phổ biến trong gia đoạn cấp của ICH. Nhưng nó được tìm thấy trong một số chó sống sót qua giai đoạn phát cấp tính của bệnh. Bệnh viêm gan ở chó làm chướng bụng do sự tích tụ của chất lỏng (Bao gồm huyết thanh và máu) hoặc do xuất huyết nội. Dấu hiệu thần kinh trung ương bao gồm: ủ rũ, mất phương hướng, co giật, hôn mê hoặc hôn mê sâu trong giai đoạn cuối của bệnh. Chó bị ảnh hưởng nhẹ có thể phục hồi sau khi hết sốt. Triệu chứng lâm sàng các biến chứng của ICH thường xuyên kéo dài 5-7 ngày trước khi giảm bớt. Phù giác mạc và viêm màng giữa của mắt thường xuất hiện khi các triệu chứng lâm sàng mất dần. Tỉ lệ tử vong dao động từ 10% -30% và thường cao nhất ở những con chó rất nhỏ. Nếu sốt ngắn, giảm bạch cầu có thể là dấu hiệu duy nhất, nhưng nếu vẫn tồn tại> 1 ngày, bệnh cấp tính phát triển.",
                    reason: "Là bệnh lây lan rất nhanh, do virus Canine Adenovirus-1 ( CAV-1 ). Các loài chó hoang dã và chó chưa được tiêm vaccine CVA-1 đều có thể mắc bệnh, đặc biệt với chó dưới một năm tuổi. Bệnh viêm gan ở chó không lây sang người. Bệnh viêm gan truyền nhiễm trên chó gây ra bởi canine adenovirus (CAV-1). Có huyết thanh đồng nhất trên toàn thế giới, tương đồng miễn dịch với adenovirus trên người. CAV-1 có kháng nguyên khác biệt so với CAV-2 (loại được sản xuất vaccin cho bệnh hô hấp trên chó). Kháng nguyên của CAV-2 đã được phân lập từ ruột chó con bị tiêu chảy xuất huyết. Từ những chó bị ho cũi chó với dấu hiệu tiêu chảy.",
                    treatment: "Không có thuốc điều trị đặc hiệu. Chủ yếu điều trị theo triệu chứng: bù nước, cân bằng điện giải, truyền dịch đường glucose, lactated Ringer và các loại kháng sinh chống viêm nhiễm kế phát, vitamin, tăng chức năng gan thận, và chăm sóc theo chỉ định của các bác sỹ thú y. Tiêm Vacxin là cách phòng tránh bệnh tốt và hiệu quả nhất",
                    description: "Bệnh cực kỳ nghiêm hiểm vì có thể gây tử vong cho chó chỉ sau 1 vài giờ.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh ghẻ Demodex",
                    symptom: "Ghẻ Demodex được phân loại thành 2 dạng: khu trú hoặc toàn thân dựa vào đánh giá tình trạng bệnh và cách xử lí đối với từng loại. Ghẻ Demodex đôi khi không gây ngứa, tuy nhiên bệnh ghẻ toàn thân và ở bàn chân có thể gây đau đớn dữ dội. Vùng rụng lông có thể bị đóng vảy và đỏ lên. Ghẻ Demodex khu trú thường có vùng tổn thương nhỏ và riêng biệt, ghẻ Demodex toàn thân có những vùng tổn thương lớn hơn và có nhiễm khuẩn thứ phát. Ghẻ Demodex khu trú được đặc trưng bởi vùng rụng lông ít (ít hơn 5 – 12 điểm), nhỏ, vùng tổn thương có giới hạn và thường xảy ra trên chó con.",
                    reason: "Chỗ ở không được vệ sinh sạch sẽ. Tiếp xúc trực tiếp với các chó bị bệnh",
                    treatment: "Dermaleen Nhỏ giọt. Dầu tắm 1 lần/ tháng,1 lần/ 2 tuần. Ghẻ Demodex khu trú Advocate®, Dermaleen, Catosal® Nhỏ giọt, dầu tắm, tiêm bắp hoặc tiêm dưới da 1 lần/ tháng,1 lần/ tuần, 0,5 – 5 ml/ con/ tuần. Ghẻ Demodex toàn thân Advocate®, Dermaleen, Amoxisol L.A, Catosal® 10% Nhỏ giọt, tiêm bắp hoặc tiêm dưới da 1 lần/ tuần, 1 lần/ tuần, 1 ml/ 10 kg thể trọng, lặp lại sau 48h. 0,5 – 5 ml/ con/ 3 ngày liên tục",
                    description: "Ghẻ Demodex toàn thân là dạng bệnh trầm trọng, gây ra tình trạng thú bị rụng lông toàn thân, da đóng vảy và tiết dịch, biểu hiện lờ đờ, sốt và nhiễm trùng huyết do nhiễm khuẩn thứ phát. Mụn, mụn mủ, đỏ da, tăng sắc tố mô là tổn thương kế phát của bệnh ghẻ Demodex toàn thân. Ghẻ Demodex toàn thân có thể xảy ra ở thú non hoặc thú trưởng thành. Thú trưởng thành thường ít bị mắc bệnh hơn nhưng khi mắc bệnh thì việc điều trị rất khó khăn. Để điều trị đạt hiệu quả cần kết hợp điều trị kí sinh trùng, nhiễm khuẩn kế phát và các nguyên nhân tiềm ẩn khác, đồng thời sử dụng các loại thuốc hỗ trợ tăng sức đề kháng.")
    Desease.create!(pet_type: 0,
                    name: "Bệnh giun tròn",
                    symptom: "Chó mất tính thèm ăn, thiếu máu gầy còm, chậm lớn, tiêu chảy, bụng to, ói mửa có lẫn cả giun. Những triệu chứng này thường thấy ở chó dưới 2 tháng tuổi. Chó có triệu chứng thần kinh, co giật. Ấu trùng di hành qua mặt thận, gan, phổi, não gây hoại tử các cơ quan và gây viêm phổi, phù thủng, xuất huyết.",
                    reason: "Ký sinh trùng này phổ biến nhất ở những vùng đầm lầy và ẩm ướt . Ký sinh trùng hoạt tính mạnh nhất vào buổi sáng, bên ngoài cơ thể vật chủ vòng đời của giun tròn là 24h, do đó con vật có thể bị nhiễm vào bất kỳ thời điểm nào trong ngày khi vô tình ăn uống thực phẩm có ký sinh trùng này. Đặc biệt là các tháng hè khi các loài ốc sên sinh sôi nảy nở nhiều mang theo kí sinh trùng giun tròn gây bệnh. Những con chó dành nhiều thời gian chơi đùa trong nước bẩn mất vệ sinh có chứa ký sinh trùng có nguy cơ cao bị nhiễm giun. Cách duy nhất để tránh lây nhiễm là để con chó tránh nguồn nước nhiễm hoặc có thể có kí sinh trùng giun tròn",
                    treatment: "– Cần kiểm tra định kỳ ít nhất 1 tháng 1 lần đối với chó con và 3 tháng 1 lần đối với chó mèo trưởng thành. Khi phát hiện thấy nhiễm định kỳ dùng thuốc để tẩy cho chó mèo. Diệt vật chủ gậm nhấm, không cho chó tiếp xúc với cáo, chó sói và các loại thú ăn thịt. Không thả rong chó. Nuôi dưỡng chăm sóc tốt để nâng cao sức đề kháng. Sát trùng nơi nhốt chó bằng NOVADINE hoặc NOVAXIDE. Khi chó mèo hoặc các loại thú ăn thịt nhiễm giun đũa nên dùng cá loại thuốc sau của công ty ANOVA như sau: Dùng thuốc NOVA-LEVA: 1 ml/ 15 kg thể trọng. Tiêm sâu vào bắp thịt, 1 liều duy nhất. Thú non dưới 6 tháng tuổi: 2 tháng tẩy giun 1 lần. Thú trên 5 tháng tuổi: 3-4 tháng tẩy giun 1 lần. Dùng thuốc NOVA MECTIN 0,25%: Phòng bệnh: Tiêm dưới da 1ml/ 6 kg thể trọng, 2 tháng 1 lần. Trị bệnh: Tiêm dưới da 1ml/ 4 kg thể trọng, 2 tháng 1 lần. Dùng thuốc NOVA MECTIN 1%: Phòng bệnh: Tiêm dưới da 1ml/ 25 kg thể trọng, 2 tháng 1 lần. Trị bệnh: Tiêm dưới da 1ml/ 16 kg thể trọng, tuần 1 lần, trong 3 tuần. Trong thời gian điều trị cần nhốt thú nơi khô ráo, sạch sẽ, tránh phụ nhiễm. Dùng thuốc NOVA-LEVASOL: 1g/ 8 kg thể trọng. Trộn đều thuốc vào 1 ít thức ăn hoặc pha vào một ít nước uống. Thú non: Mỗi 2 tháng xổ 1 lần. Thú lớn: Mỗi 6 tháng xổ 1 lần.",
                    description: "Ký sinh trùng giun tròn bắt đầu một chu kì bằng việc giao phối và sản sinh trứng trong ruột sau đó trứng theo phân ra ngoài truyền lây cho động vật khác. Một khi trứng đã rời khỏi cơ thể chúng sẽ bám vào các cây thủy sinh trong nước và tìm một cơ thể vật chủ (thường là ốc sên) nơi nó tự tái sinh vô tính thành nhiều bào tử tạo thành dạng ấu trùng giống như túi. Các ấu trùng này đi qua đường máu vào ruột sinh sôi nảy nở thành sán đực và sán cái sinh sản tiếp tục và di chuyển đến các cơ quan bên trong cơ thể để gây bệnh.")

puts "8. Seeding Service"
random = Random.new
20.times do
  Service.create!(name: FFaker::Name.unique.name, price: random.rand(20000..50000))
end


puts "9. Seeding Pet"
User.all.each do |user|
  5.times do
    Pet.create!(user_id: user.id, name: FFaker::Name.unique.name, image: "/app/assets/images/150x150.jpg", gender: random.rand(0..1), type_pet: random.rand(0..1), dob: DateTime.now)
  end
end
